codecov:
    token: 6489d317-2c86-4cfc-9b7c-d6d7353152d1
    notify:
      require_ci_to_pass: no

  coverage:
    precision: 2
    round: down
    range: "70...100"

    status:
      project: yes
      patch: yes
      changes: no

  parsers:
    gcov:
      branch_detection:
        conditional: yes
        loop: yes
        method: no
        macro: no

  comment:
    layout: "header, diff, files"
    behavior: default
    require_changes: yes

  github_checks:
    annotations: false
