# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test And Deploy To Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.13.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: NODE_ENV=production npm ci
    - run: npm run build
      env:
        REACT_APP_FIREBASE_apiKey: ${{ secrets.REACT_APP_FIREBASE_apiKey }}
        REACT_APP_FIREBASE_authDomain: ${{ secrets.REACT_APP_FIREBASE_authDomain }}
        REACT_APP_FIREBASE_databaseURL: ${{ secrets.REACT_APP_FIREBASE_databaseURL }}
        REACT_APP_FIREBASE_projectId: ${{ secrets.REACT_APP_FIREBASE_projectId }}
        REACT_APP_FIREBASE_storageBucket: ${{ secrets.REACT_APP_FIREBASE_storageBucket }}
        REACT_APP_FIREBASE_messagingSenderId: ${{ secrets.REACT_APP_FIREBASE_messagingSenderId }}
        REACT_APP_FIREBASE_appId: ${{ secrets.REACT_APP_FIREBASE_appId }}
        REACT_APP_FIREBASE_measurementId: ${{ secrets.REACT_APP_FIREBASE_measurementId }}
    - name: Deploy to Production
      uses: trendyminds/github-actions-rsync@master
      with:
        RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
        RSYNC_TARGET: ${{ secrets.SSH_PATH }}
        RSYNC_SOURCE: build
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        SSH_USERNAME: ${{ secrets.SSH_USER }}
        SSH_HOSTNAME: ${{ secrets.BEACON_HILLS }}

